# -*- coding: utf-8 -*-
"""analizar_declaracion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14lAsJtdedXRNB57ftcwiwUphqwa4VG0Q

STREAMLIT
"""

import streamlit as st
import numpy as np
import pandas as pd
import predecir_dec_violencia as pred

st.title('Violencia de género')

st.subheader("Declaración")
text1=st.text_input("Ingresar url de la declaración para analizar el contenido y verificar la presencia de los distintos tipos de  violencia")

if st.button('cargar'):
    if text1 !="" and text1 is not None:
        contenido=pred.obtener_declaracion(text1)
        prediccion=pd.DataFrame(pred.predecir_violencia(text1))
        tipos_v=["Violencia de género", "Violencia física", "Violencia psiquica", "Violencia económica",
                                        "violencia sexual", "violencia social", "violencia ambiental", "violencia simbólica"]
        resultado=pd.DataFrame(tipos_v, columns=["Tipos_violencia"])
        resultado["Presente en caso"]=pd.DataFrame(prediccion>0.5).transpose()
        resultado["Probabilidad"]=pd.DataFrame(prediccion.transpose())
        resultado = resultado.rename(columns={'Tipos_violencia':'index'}).set_index('index')
        resultado  
        st.subheader("Probabilidades")
        #grafico=pd.DataFrame(resultado.iloc[:,[0,2]])
        st.bar_chart(resultado["Probabilidad"])
        st.subheader("Texto de la declaración")
        st.write(contenido)  
    else:
        st.write('Ingrese una url para poder continuar')

        

    
    


